
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: syncpad-backend
    env_file:
      - ./server/.env
    ports:
      - "3030:3030"
    depends_on:
      - db
    volumes:
      - ./server:/app

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: syncpad-frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - VITE_API_URL=http://localhost:3030

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
